default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  user: medical_user
  password: medical_user
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: medical_development

test:
  <<: *default
  database: medical_test

production:
  <<: *default
  database: medical_production
